/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as ColleaguesRouteImport } from './routes/colleagues'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RestaurantsIdRouteImport } from './routes/restaurants.$id'
import { Route as ExpenseIdRouteImport } from './routes/expense.$id'
import { Route as ColleaguesColleagueIdRouteImport } from './routes/colleagues.$colleagueId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ColleaguesRoute = ColleaguesRouteImport.update({
  id: '/colleagues',
  path: '/colleagues',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsIdRoute = RestaurantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RestaurantsRoute,
} as any)
const ExpenseIdRoute = ExpenseIdRouteImport.update({
  id: '/expense/$id',
  path: '/expense/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ColleaguesColleagueIdRoute = ColleaguesColleagueIdRouteImport.update({
  id: '/$colleagueId',
  path: '/$colleagueId',
  getParentRoute: () => ColleaguesRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/colleagues': typeof ColleaguesRouteWithChildren
  '/expenses': typeof ExpensesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/colleagues/$colleagueId': typeof ColleaguesColleagueIdRoute
  '/expense/$id': typeof ExpenseIdRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/colleagues': typeof ColleaguesRouteWithChildren
  '/expenses': typeof ExpensesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/colleagues/$colleagueId': typeof ColleaguesColleagueIdRoute
  '/expense/$id': typeof ExpenseIdRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/colleagues': typeof ColleaguesRouteWithChildren
  '/expenses': typeof ExpensesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurants': typeof RestaurantsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/colleagues/$colleagueId': typeof ColleaguesColleagueIdRoute
  '/expense/$id': typeof ExpenseIdRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/colleagues'
    | '/expenses'
    | '/forgot-password'
    | '/login'
    | '/payments'
    | '/reset-password'
    | '/restaurants'
    | '/settings'
    | '/setup'
    | '/auth/callback'
    | '/colleagues/$colleagueId'
    | '/expense/$id'
    | '/restaurants/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/colleagues'
    | '/expenses'
    | '/forgot-password'
    | '/login'
    | '/payments'
    | '/reset-password'
    | '/restaurants'
    | '/settings'
    | '/setup'
    | '/auth/callback'
    | '/colleagues/$colleagueId'
    | '/expense/$id'
    | '/restaurants/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/colleagues'
    | '/expenses'
    | '/forgot-password'
    | '/login'
    | '/payments'
    | '/reset-password'
    | '/restaurants'
    | '/settings'
    | '/setup'
    | '/auth/callback'
    | '/colleagues/$colleagueId'
    | '/expense/$id'
    | '/restaurants/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  ColleaguesRoute: typeof ColleaguesRouteWithChildren
  ExpensesRoute: typeof ExpensesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PaymentsRoute: typeof PaymentsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RestaurantsRoute: typeof RestaurantsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ExpenseIdRoute: typeof ExpenseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colleagues': {
      id: '/colleagues'
      path: '/colleagues'
      fullPath: '/colleagues'
      preLoaderRoute: typeof ColleaguesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/$id': {
      id: '/restaurants/$id'
      path: '/$id'
      fullPath: '/restaurants/$id'
      preLoaderRoute: typeof RestaurantsIdRouteImport
      parentRoute: typeof RestaurantsRoute
    }
    '/expense/$id': {
      id: '/expense/$id'
      path: '/expense/$id'
      fullPath: '/expense/$id'
      preLoaderRoute: typeof ExpenseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colleagues/$colleagueId': {
      id: '/colleagues/$colleagueId'
      path: '/$colleagueId'
      fullPath: '/colleagues/$colleagueId'
      preLoaderRoute: typeof ColleaguesColleagueIdRouteImport
      parentRoute: typeof ColleaguesRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ColleaguesRouteChildren {
  ColleaguesColleagueIdRoute: typeof ColleaguesColleagueIdRoute
}

const ColleaguesRouteChildren: ColleaguesRouteChildren = {
  ColleaguesColleagueIdRoute: ColleaguesColleagueIdRoute,
}

const ColleaguesRouteWithChildren = ColleaguesRoute._addFileChildren(
  ColleaguesRouteChildren,
)

interface RestaurantsRouteChildren {
  RestaurantsIdRoute: typeof RestaurantsIdRoute
}

const RestaurantsRouteChildren: RestaurantsRouteChildren = {
  RestaurantsIdRoute: RestaurantsIdRoute,
}

const RestaurantsRouteWithChildren = RestaurantsRoute._addFileChildren(
  RestaurantsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  ColleaguesRoute: ColleaguesRouteWithChildren,
  ExpensesRoute: ExpensesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PaymentsRoute: PaymentsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RestaurantsRoute: RestaurantsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ExpenseIdRoute: ExpenseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
